import { useMemo } from "react";
import type { InspectorPanelProps } from "../components/InspectorPanel";

export function useInspectorPanelProps(
  props: InspectorPanelProps,
): InspectorPanelProps {
  return useMemo(() => props, [
    props.showInspector,
    props.selectedModel,
    props.inspectorTab,
    props.inspectorDensity,
    props.inspectorTabs,
    props.inspectorTabRefs,
    props.activeTabTitle,
    props.activeTabPath,
    props.activeTabBranch,
    props.activeTabChanged,
    props.noActivity,
    props.failedBlocks,
    props.focusedFailedBlock,
    props.analyzeCache,
    props.recentBlocks,
    props.commandMenuIndex,
    props.quickActionsExpanded,
    props.inspectorMoreButtonRefs,
    props.inspectorMenuFirstActionRefs,
    props.inspectorQuickActionsToggleRef,
    props.inspectorQuickActionsAdvancedRef,
    props.onDensityToggle,
    props.onClose,
    props.onTabSelect,
    props.onTabKeyDown,
    props.onFocusFailedBlock,
    props.onAnalyzeFailedBlock,
    props.onCopyFailedOutput,
    props.onCopyAnalyzePrompt,
    props.onLoadAnalyzePromptToAiBar,
    props.onSelectBlock,
    props.onCopyAnalyzeResult,
    props.onClearAnalyzeCache,
    props.onCopySuggestedCommand,
    props.onLoadSuggestedCommandToAiBar,
    props.onApplySuggestedCommand,
    props.onRerunBlock,
    props.onCommandMenuRowBlurCapture,
    props.onSuggestedCommandRowKeyDown,
    props.onCompactMenuKeyDown,
    props.onOpenCompactMenu,
    props.onCloseCommandMenu,
    props.onQuickActionsToggle,
    props.onQuickActionsToggleKeyDown,
    props.onQuickActionsAdvancedKeyDown,
    props.onToggleProjectBin,
    props.onOpenWorkspace,
    props.onOpenHistory,
    props.onOpenDiffReview,
    props.onOpenFailedBlock,
    props.scriptLibrary,
  ]);
}

